Resources:
  RestAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: "Macro Test API"

  SimpleResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt RestAPI.RootResourceId
      PathPart: "message"
      RestApiId: !Ref RestAPI
  SimpleResourcePath:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref SimpleResource
      PathPart: "{vpcid}"
      RestApiId: !Ref RestAPI

  GetMethod:
    Type: AWS::ApiGateway::Method
    'Fn::Transform':
      - Name: SimpleAPI
    Properties:
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: 200
      RestApiId:
        Ref: RestAPI
      ResourceId:
        Ref: SimpleResourcePath
      HttpMethod: GET
      Integration:
        Credentials:
          Fn::GetAtt:
            - MyRole
            - Arn
        Service: ec2
        Action:
         Name: CreateSubnet
         Parameters:
          - VpcId: method.request.path.vpcid
          - CidrBlock: method.request.querystring.cidr
        ResponseMaps:
          Success:
            - requestId: "request-id"
            - subnet: "subnet"
          InvalidInput:
            - Message: "error-messages"
          Failure: #TODO
  MyRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess